// Shared light theme styles for all operation pages

export const L = {
  page: {
    padding: '24px',
    background: '#f8f9fc',
    minHeight: '100%',
    fontFamily: 'DM Sans, sans-serif',
    overflowY: 'auto' as const,
  },
  tableWrap: {
    background: '#fff',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    overflow: 'hidden',
  },
  th: {
    padding: '10px 16px',
    textAlign: 'left' as const,
    fontSize: '11px',
    fontWeight: 600,
    color: '#6b7280',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    background: '#f9fafb',
    borderBottom: '1px solid #e5e7eb',
  },
  td: {
    padding: '12px 16px',
    fontSize: '13px',
    color: '#6b7280',
    borderBottom: '1px solid #f3f4f6',
  },
  tdPrimary: {
    padding: '12px 16px',
    fontSize: '13px',
    color: '#111827',
    fontWeight: 600,
    borderBottom: '1px solid #f3f4f6',
  },
  btnPrimary: {
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '9px 16px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex' as const,
    alignItems: 'center' as const,
    gap: '6px',
  },
  btnSecondary: {
    background: '#f9fafb',
    color: '#6b7280',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '9px 16px',
    fontSize: '13px',
    cursor: 'pointer',
  },
  btnValidate: {
    background: '#f0fdf4',
    color: '#16a34a',
    border: '1px solid #bbf7d0',
    borderRadius: '6px',
    padding: '5px 12px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnGhost: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    display: 'flex' as const,
    alignItems: 'center' as const,
  },
  btnOutline: {
    background: 'transparent',
    color: '#6366f1',
    border: '1px solid #c7d2fe',
    borderRadius: '8px',
    padding: '7px 14px',
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex' as const,
    alignItems: 'center' as const,
    gap: '6px',
  },
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(0,0,0,0.4)',
    display: 'flex' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    zIndex: 50,
  },
  modal: {
    background: '#fff',
    borderRadius: '16px',
    padding: '28px',
    width: '520px',
    maxWidth: '95vw',
    maxHeight: '90vh',
    overflowY: 'auto' as const,
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
  },
  modalTitle: {
    fontFamily: 'Syne, sans-serif',
    fontWeight: 700,
    fontSize: '16px',
    color: '#111827',
    margin: 0,
  },
  modalSub: {
    color: '#9ca3af',
    fontSize: '12px',
    marginTop: '3px',
  },
  label: {
    display: 'block' as const,
    fontSize: '11px',
    fontWeight: 600,
    color: '#6b7280',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    marginBottom: '5px',
  },
  input: {
    width: '100%',
    padding: '9px 12px',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    fontSize: '13px',
    color: '#111827',
    background: '#fff',
    boxSizing: 'border-box' as const,
    outline: 'none',
    fontFamily: 'DM Sans, sans-serif',
  },
  select: {
    width: '100%',
    padding: '9px 12px',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    fontSize: '13px',
    color: '#111827',
    background: '#fff',
    boxSizing: 'border-box' as const,
    outline: 'none',
    fontFamily: 'DM Sans, sans-serif',
    appearance: 'none' as const,
  },
  sectionTitle: {
    fontFamily: 'Syne, sans-serif',
    fontWeight: 700,
    fontSize: '18px',
    color: '#111827',
  },
};

export const statusStyle = (status: string): React.CSSProperties => {
  const map: Record<string, { bg: string; color: string; border: string }> = {
    DRAFT:    { bg: '#f3f4f6', color: '#6b7280', border: '#e5e7eb' },
    WAITING:  { bg: '#fffbeb', color: '#d97706', border: '#fde68a' },
    READY:    { bg: '#eff6ff', color: '#2563eb', border: '#bfdbfe' },
    DONE:     { bg: '#f0fdf4', color: '#16a34a', border: '#bbf7d0' },
    CANCELED: { bg: '#fef2f2', color: '#dc2626', border: '#fecaca' },
  };
  const s = map[status] || map.DRAFT;
  return {
    display: 'inline-block',
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 600,
    background: s.bg,
    color: s.color,
    border: `1px solid ${s.border}`,
  };
};

export const Loader = () => (
  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: '#9ca3af', fontSize: '13px' }}>
    Loading...
  </div>
);